name: push-on-tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scheme: [full, medium, basic, minimal]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
              TEXLIVE_SCHEME=${{ matrix.scheme }}
          push: true
          tags: |
            flowchartsman/texlive-multiarch:${{ matrix.scheme }}-latest
            flowchartsman/texlive-multiarch:${{ matrix.schema }}-${{github.ref_name}}
